name: Загрузка историй на сервер

on:
  push:
    branches: [ "main" ]
    types: [closed]
  pull_request:
    branches: [ "main" ]
    types: [closed]
  
  # для вызова с сервера
  repository_dispatch:
    types: [on-demand]

  # ручной запуск
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Проверка синтаксиса файлов
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Validate files
      uses: anyone-developer/anyone-validate-json@main
      with:
        file-extension: '.sm,.json,.cqe'
        ignore-files: 'README.md,changelog.txt'
        ignore-directories: '.github'
        read-path: '.'
        
  web-deploy:
    needs: check
    name: Загрузка на сервер, обновление
    runs-on: ubuntu-latest
    steps:
    - name: Download all stories
      uses: actions/checkout@v2
      
    - name: Zip stories
      run: zip release.zip ./* -r
      
    - name: Upload stories to server
      uses: alikamal1/Form_Data_HTTP_POST_Action@v.1.0
      with:
        # The Endpoint of post request
        url: ${{env.UPLOAD_STORIES_ENDPOINT}}
        # The Headers of post request
        headers: '{"t":"${{secrets.UPLOAD_STORIES_TOKEN}}"}'
        file: release.zip          
