name: Загрузка историй на сервер

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # ручной запуск
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Проверка синтаксиса файлов
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Validate files
      uses: anyone-developer/anyone-validate-json@main
      with:
        file-extension: '.sm,.json,.cqe'
        ignore-files: 'README.md,changelog.txt'
        ignore-directories: '.github'
        read-path: '.'
        
  web-deploy:
    needs: check
    name: Загрузка на сервер
    runs-on: ubuntu-latest
    steps:
    - name: Download all stories
      uses: actions/checkout@v2
      
    - name: Sync files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        source: .
        target: /data/pdanetwork/stories
        rm: true
        overwrite: true
        

  notify:
    needs: web-deploy
    name: Обновление на сервере
    runs-on: ubuntu-latest
    steps:
    - name: Update stories trigger
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
        webhook_secret: "secret"
       
