name: Загрузка историй на сервер

on:
  push:
    branches: [ "main" ]
    types: [closed]
  pull_request:
    branches: [ "main" ]
    types: [closed]
  
  # для вызова с сервера
  repository_dispatch:
    types: [on-demand]

  # ручной запуск
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Проверка синтаксиса файлов
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Validate files
      uses: anyone-developer/anyone-validate-json@main
      with:
        file-extension: '.sm,.json,.cqe'
        ignore-files: 'README.md,changelog.txt'
        ignore-directories: '.github'
        read-path: '.'
        
  web-deploy:
    needs: check
    name: Загрузка на сервер, обновление
    runs-on: ubuntu-latest
    steps:
    - name: Download all files
      uses: actions/checkout@v2
      
    - name: Compress files to ZIP
      run: zip release.zip ./* -r
      
    - name: Create ZIP - release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: |
          release.zip
          
    - name: Trigger server to download release
      uses: distributhor/workflow-webhook@v2
      env:
       webhook_url: ${{ secrets.WEBHOOK_URL }}
       webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
       webhook_secret: "secret"
