name: Загрузка историй на сервер

on:
  push:
    branches: [ "main" ]
    types: [closed]
  pull_request:
    branches: [ "main" ]
    types: [closed]
  
  # для вызова с сервера
  repository_dispatch:
    types: [on-demand]

  # ручной запуск
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Проверка синтаксиса файлов
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Validate files
      uses: anyone-developer/anyone-validate-json@main
      with:
        file-extension: '.sm,.json,.cqe'
        ignore-files: 'README.md,changelog.txt'
        ignore-directories: '.github'
        read-path: '.'
        
  web-deploy:
    needs: check
    name: Команда серверу загрузить файлы
    runs-on: ubuntu-latest
    steps:
    - name: Trigger server to download files
      uses: distributhor/workflow-webhook@v2
      env:
       webhook_url: ${{ secrets.WEBHOOK_URL }}
       webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
       webhook_secret: "secret"
