name: Загрузка историй на сервер

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # ручной запуск
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy stories to server
    runs-on: ubuntu-latest
    steps:
    - name: Download all stories
      uses: actions/checkout@v2
        
    - name: Syntax check
      uses: limitusus/json-syntax-check@v1    
        
    - name: Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: 34.138.20.76
        remote-user: maksim_prygunov
        private-ssh-key: ${{ secrets.private_key }}
        destination-path: /data/pdanetwork/stories/
       
