name: Загрузка историй на сервер

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # ручной запуск
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Проверка синтаксиса файлов
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Validate files
      uses: anyone-developer/anyone-validate-json@main
      with:
        file-extension: '.sm,.json,.cqe'
        ignore-files: 'README.md,changelog.txt'
        ignore-directories: '.github'
        read-path: '.'
        
  web-deploy:
    needs: check
    name: Загрузка на сервер
    runs-on: ubuntu-latest
    steps:
    - name: Download all stories
      uses: actions/checkout@v2
        
    - name: Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: 34.138.20.76
        remote-user: maksim_prygunov
        private-ssh-key: ${{ secrets.private_key }}
        destination-path: /data/pdanetwork/stories/
       
