name: Загрузка историй на сервер

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # ручной запуск
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy stories to server
    runs-on: ubuntu-latest
    steps:
    - name: Download all stories
      uses: actions/checkout@v2
        
    - name: Upload to FTP server
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: 35.185.126.21
        user: admin-pda
        password: ${{ secrets.password }}
        remoteDir: "stories"
       
